version: '3.8'

services:
  agentic-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped

  # Optional: Add Redis for production session storage
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped